################################################################
#
# This is the default configuration file of Kitodo Mediaserver
#
# DO NOT MAKE ANY LOCAL CHANGES TO THIS FILE!
#
# You can override configurations in thie fils in local.yml
#
#################################################################

spring:
  datasource:
    url: jdbc:mysql://localhost/mediaserver?autoReconnect=true&useSSL=false
    username: kitodo
    password: kitodo


fileserver:
  filePathPattern: /files/{workId}/**
